CREATE TABLE "activities" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint DEFAULT NULL,
  "accion" varchar(255) NOT NULL,
  "tipo_entidad" varchar(255) NOT NULL,
  "entidad_id" bigint DEFAULT NULL,
  "descripcion" varchar(255) NOT NULL,
  "direccion_ip" varchar(45) DEFAULT NULL,
  "navegador" text DEFAULT NULL,
  "valores_anteriores" text DEFAULT NULL,
  "valores_nuevos" text DEFAULT NULL,
  "datos_peticion" text DEFAULT NULL,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  CONSTRAINT "activities_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL
) ;

CREATE TABLE "areas" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "codigo" varchar(50) NOT NULL,
  "activo" smallint NOT NULL DEFAULT 1,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  UNIQUE ("codigo")
) ;

CREATE TABLE "cache" (
  "key" varchar(255) NOT NULL,
  "value" text NOT NULL,
  "expiration" integer NOT NULL,
  PRIMARY KEY ("key")
) ;

CREATE TABLE "cache_locks" (
  "key" varchar(255) NOT NULL,
  "owner" varchar(255) NOT NULL,
  "expiration" integer NOT NULL,
  PRIMARY KEY ("key")
) ;

CREATE TABLE "cargos" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "codigo" varchar(50) NOT NULL,
  "activo" smallint NOT NULL DEFAULT 1,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  UNIQUE ("codigo")
) ;

CREATE TABLE "changelogs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_autor" varchar(255) NOT NULL,
  "correo_autor" varchar(255) NOT NULL,
  "hash_commit" varchar(40) NOT NULL,
  "mensaje_commit" text NOT NULL,
  "descripcion" text DEFAULT NULL,
  "tipo" varchar(255) NOT NULL DEFAULT 'change',
  "seccion" varchar(255) DEFAULT NULL,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  UNIQUE ("hash_commit")
) ;

CREATE TABLE "documentos" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "expediente_id" bigint NOT NULL,
  "nombre" varchar(255) NOT NULL,
  "archivo" varchar(255) NOT NULL,
  "estado" varchar(50) CHECK (VALUE IN ('en_revision', 'aprobado', 'rechazado')) NOT NULL DEFAULT 'en_revision',
  "nota_rechazo" text DEFAULT NULL,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  CONSTRAINT "documentos_expediente_id_foreign" FOREIGN KEY ("expediente_id") REFERENCES "expedientes" ("id") ON DELETE CASCADE
) ;

CREATE TABLE "expedientes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trabajador_id" bigint NOT NULL,
  "solicitud_id" bigint NOT NULL,
  "foto_carnet" varchar(255) DEFAULT NULL,
  "estado_global" integer NOT NULL DEFAULT 0,
  "notas_admin" text DEFAULT NULL,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  CONSTRAINT "expedientes_solicitud_id_foreign" FOREIGN KEY ("solicitud_id") REFERENCES "solicitudes" ("id") ON DELETE CASCADE,
  CONSTRAINT "expedientes_trabajador_id_foreign" FOREIGN KEY ("trabajador_id") REFERENCES "trabajadores" ("id") ON DELETE CASCADE
) ;

CREATE TABLE "failed_jobs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" varchar(255) NOT NULL,
  "connection" text NOT NULL,
  "queue" text NOT NULL,
  "payload" text NOT NULL,
  "exception" text NOT NULL,
  "failed_at" timestamp NOT NULL DEFAULT current_timestamp(),
  UNIQUE ("uuid")
) ;

CREATE TABLE "grados" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) NOT NULL,
  "codigo" varchar(20) NOT NULL,
  "activo" smallint NOT NULL DEFAULT 1,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  UNIQUE ("codigo")
) ;

CREATE TABLE "job_batches" (
  "id" varchar(255) NOT NULL,
  "name" varchar(255) NOT NULL,
  "total_jobs" integer NOT NULL,
  "pending_jobs" integer NOT NULL,
  "failed_jobs" integer NOT NULL,
  "failed_job_ids" text NOT NULL,
  "options" text DEFAULT NULL,
  "cancelled_at" integer DEFAULT NULL,
  "created_at" integer NOT NULL,
  "finished_at" integer DEFAULT NULL
) ;

CREATE TABLE "jobs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "queue" varchar(255) NOT NULL,
  "payload" text NOT NULL,
  "attempts" tinyinteger unsigned NOT NULL,
  "reserved_at" integer unsigned DEFAULT NULL,
  "available_at" integer unsigned NOT NULL,
  "created_at" integer unsigned NOT NULL
) ;

CREATE TABLE "migrations" (
  "id" integer unsigned NOT NULL,
  "migration" varchar(255) NOT NULL,
  "batch" integer NOT NULL
) ;

CREATE TABLE "niveles_instruccion" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "codigo" varchar(20) NOT NULL,
  "activo" smallint NOT NULL DEFAULT 1,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  UNIQUE ("codigo")
) ;

CREATE TABLE "nominas" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trabajador_id" bigint NOT NULL,
  "periodo" date NOT NULL,
  "sueldo_base" numeric(12,2) DEFAULT NULL,
  "prima_familiar" numeric(12,2) DEFAULT NULL,
  "prima_hijo" numeric(12,2) DEFAULT NULL,
  "prima_hijos_discapacidad" numeric(12,2) DEFAULT NULL,
  "prima_actividad_universitaria" numeric(12,2) DEFAULT NULL,
  "prima_profesionalizacion" numeric(12,2) DEFAULT NULL,
  "prima_responsabilidad" numeric(12,2) DEFAULT NULL,
  "complemento_prima_responsabilidad" numeric(12,2) DEFAULT NULL,
  "prima_antiguedad" numeric(12,2) DEFAULT NULL,
  "cesta_ticket" numeric(12,2) DEFAULT NULL,
  "total_asignacion" numeric(12,2) DEFAULT NULL,
  "sso" numeric(12,2) DEFAULT NULL,
  "lpf" numeric(12,2) DEFAULT NULL,
  "faov" numeric(12,2) DEFAULT NULL,
  "aporte_ipasme" numeric(12,2) DEFAULT NULL,
  "aporte_caja_ahorro" numeric(12,2) DEFAULT NULL,
  "prestamo_caja_ahorro" numeric(12,2) DEFAULT NULL,
  "isr" numeric(12,2) NOT NULL DEFAULT 0.00,
  "horas_extras" numeric(12,2) NOT NULL DEFAULT 0.00,
  "total_deduccion" numeric(12,2) DEFAULT NULL,
  "neto_a_cobrar" numeric(12,2) DEFAULT NULL,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  UNIQUE ("trabajador_id","periodo"),
  CONSTRAINT "nominas_trabajador_id_foreign" FOREIGN KEY ("trabajador_id") REFERENCES "trabajadores" ("id") ON DELETE CASCADE
) ;

CREATE TABLE "notifications" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "from_user_id" bigint DEFAULT NULL,
  "titulo" varchar(255) NOT NULL,
  "mensaje" text NOT NULL,
  "tipo" varchar(255) NOT NULL DEFAULT 'info',
  "leida" smallint NOT NULL DEFAULT 0,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  CONSTRAINT "notifications_from_user_id_foreign" FOREIGN KEY ("from_user_id") REFERENCES "users" ("id") ON DELETE SET NULL,
  CONSTRAINT "notifications_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
) ;

CREATE TABLE "password_reset_tokens" (
  "email" varchar(255) NOT NULL,
  "token" varchar(255) NOT NULL,
  "created_at" timestamp(0) without time zone,
  PRIMARY KEY ("email")
) ;

CREATE TABLE "prestaciones" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trabajador_id" bigint NOT NULL,
  "anios_servicio" integer NOT NULL,
  "monto" numeric(12,2) NOT NULL,
  "detalles" text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid("detalles")),
  "sueldo_integral" numeric(12,2) NOT NULL DEFAULT 0.00,
  "total_primas" numeric(12,2) NOT NULL DEFAULT 0.00,
  "porcentaje_jubilacion" numeric(5,2) NOT NULL DEFAULT 100.00,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  CONSTRAINT "prestaciones_trabajador_id_foreign" FOREIGN KEY ("trabajador_id") REFERENCES "trabajadores" ("id") ON DELETE CASCADE
) ;

CREATE TABLE "prestaciones_sociales" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trabajador_id" bigint NOT NULL,
  "fecha_calculo" date NOT NULL,
  "salario_integral_promedio" numeric(12,2) DEFAULT NULL,
  "antiguedad_dias" integer DEFAULT NULL,
  "antiguedad_monto" numeric(12,2) DEFAULT NULL,
  "intereses_prestaciones" numeric(12,2) DEFAULT NULL,
  "total_prestaciones" numeric(12,2) DEFAULT NULL,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  CONSTRAINT "prestaciones_sociales_trabajador_id_foreign" FOREIGN KEY ("trabajador_id") REFERENCES "trabajadores" ("id") ON DELETE CASCADE
) ;

CREATE TABLE "primas" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(50) NOT NULL,
  "nombre" varchar(150) NOT NULL,
  "monto" numeric(12,2) NOT NULL DEFAULT 0.00,
  "valor" numeric(12,2) NOT NULL DEFAULT 0.00,
  "fecha_vigencia" date DEFAULT NULL,
  "activo" smallint NOT NULL DEFAULT 1,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  UNIQUE ("codigo")
) ;

CREATE TABLE "sessions" (
  "id" varchar(255) NOT NULL,
  "user_id" bigint DEFAULT NULL,
  "ip_address" varchar(45) DEFAULT NULL,
  "user_agent" text DEFAULT NULL,
  "payload" text NOT NULL,
  "last_activity" integer NOT NULL
) ;

CREATE TABLE "solicitudes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trabajador_id" bigint NOT NULL,
  "fecha_solicitud" date NOT NULL,
  "periodo" varchar(20) DEFAULT NULL,
  "tipo_jubilacion" varchar(100) DEFAULT NULL,
  "observaciones" text DEFAULT NULL,
  "estado" varchar(50) CHECK (VALUE IN ('pendiente', 'revision', 'aprobado', 'rechazado')) NOT NULL,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  "deleted_at" timestamp(0) without time zone,
  CONSTRAINT "solicitudes_trabajador_id_foreign" FOREIGN KEY ("trabajador_id") REFERENCES "trabajadores" ("id") ON DELETE CASCADE
) ;

CREATE TABLE "sueldos" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grado_id" bigint NOT NULL,
  "nivel_instruccion_id" bigint NOT NULL,
  "sueldo_base" numeric(12,2) NOT NULL,
  "complemento_prima_cargo" numeric(12,2) NOT NULL DEFAULT 0.00,
  "porcentaje_prima_cargo" numeric(5,2) NOT NULL DEFAULT 0.00,
  "activo" smallint NOT NULL DEFAULT 1,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  UNIQUE ("grado_id","nivel_instruccion_id"),
  CONSTRAINT "sueldos_grado_id_foreign" FOREIGN KEY ("grado_id") REFERENCES "grados" ("id") ON DELETE CASCADE,
  CONSTRAINT "sueldos_nivel_instruccion_id_foreign" FOREIGN KEY ("nivel_instruccion_id") REFERENCES "niveles_instruccion" ("id") ON DELETE CASCADE
) ;

CREATE TABLE "tipos_contrato" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "codigo" varchar(50) NOT NULL,
  "activo" smallint NOT NULL DEFAULT 1,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  UNIQUE ("codigo")
) ;

CREATE TABLE "tipos_jubilacion" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "codigo" varchar(50) NOT NULL,
  "activo" smallint NOT NULL DEFAULT 1,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  UNIQUE ("codigo")
) ;

CREATE TABLE "trabajadores" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_empleado" varchar(20) DEFAULT NULL,
  "cedula" varchar(255) NOT NULL,
  "nombres" varchar(255) NOT NULL,
  "apellidos" varchar(255) NOT NULL,
  "cuenta_bancaria" varchar(255) DEFAULT NULL,
  "genero" varchar(50) CHECK (VALUE IN ('M', 'F')) NOT NULL,
  "grado_nivel" varchar(255) NOT NULL,
  "grado_id" bigint DEFAULT NULL,
  "cargo" varchar(255) NOT NULL,
  "cargo_id" bigint DEFAULT NULL,
  "unidad_departamento" varchar(255) NOT NULL,
  "area_id" bigint DEFAULT NULL,
  "sueldo_base" numeric(12,2) DEFAULT NULL,
  "denominacion_salario" varchar(255) DEFAULT NULL,
  "tabulador" varchar(50) DEFAULT NULL,
  "porcentaje_prima_cargo" numeric(5,2) DEFAULT NULL,
  "complemento_prima_cargo" numeric(12,2) DEFAULT NULL,
  "es_jefe_coordinador" smallint NOT NULL DEFAULT 0,
  "cesta_ticket" numeric(12,2) DEFAULT NULL,
  "prima_profesionalizacion" numeric(12,2) DEFAULT NULL,
  "sugau" numeric(12,2) DEFAULT NULL,
  "afiliacion_sifaiuty" varchar(50) DEFAULT NULL,
  "asignacion" varchar(50) CHECK (VALUE IN ('Manual', 'Nomina')) NOT NULL DEFAULT 'Manual',
  "fecha_nacimiento" date NOT NULL,
  "edad" integer NOT NULL,
  "fecha_ingreso" date NOT NULL,
  "anos_servicio_inst" integer NOT NULL,
  "anos_servicio_externo" integer NOT NULL,
  "total_anos_servicio" integer NOT NULL,
  "nivel_instruccion" integer NOT NULL,
  "nivel_instruccion_id" bigint DEFAULT NULL,
  "nivel_educativo_texto" varchar(100) DEFAULT NULL,
  "tipo_contrato_id" bigint DEFAULT NULL,
  "numero_hijos" integer NOT NULL,
  "hijos_discapacidad" integer NOT NULL DEFAULT 0,
  "actividad_universitaria" smallint NOT NULL DEFAULT 0,
  "porcentaje_antiguedad" numeric(5,2) NOT NULL DEFAULT 0.00,
  "porcentaje_caja_ahorro" numeric(5,2) NOT NULL DEFAULT 0.00,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  "deleted_at" timestamp(0) without time zone,
  CONSTRAINT "trabajadores_area_id_foreign" FOREIGN KEY ("area_id") REFERENCES "areas" ("id") ON DELETE SET NULL,
  CONSTRAINT "trabajadores_cargo_id_foreign" FOREIGN KEY ("cargo_id") REFERENCES "cargos" ("id") ON DELETE SET NULL,
  CONSTRAINT "trabajadores_grado_id_foreign" FOREIGN KEY ("grado_id") REFERENCES "grados" ("id") ON DELETE SET NULL,
  CONSTRAINT "trabajadores_nivel_instruccion_id_foreign" FOREIGN KEY ("nivel_instruccion_id") REFERENCES "niveles_instruccion" ("id") ON DELETE SET NULL,
  CONSTRAINT "trabajadores_tipo_contrato_id_foreign" FOREIGN KEY ("tipo_contrato_id") REFERENCES "tipos_contrato" ("id") ON DELETE SET NULL
) ;

CREATE TABLE "users" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "apellido" varchar(255) DEFAULT NULL,
  "correo" varchar(255) NOT NULL,
  "telefono" varchar(255) DEFAULT NULL,
  "fecha_nacimiento" date DEFAULT NULL,
  "avatar" varchar(255) DEFAULT NULL,
  "correo_verificado_en" datetime DEFAULT NULL,
  "password" varchar(255) NOT NULL,
  "rol" varchar(50) CHECK (VALUE IN ('usuario', 'admin', 'superadmin')) NOT NULL DEFAULT 'usuario',
  "tema" varchar(255) NOT NULL DEFAULT 'light',
  "idioma" varchar(255) NOT NULL DEFAULT 'es',
  "color_acento" varchar(255) NOT NULL DEFAULT '#1a365d',
  "verificacion_dos_pasos" smallint NOT NULL DEFAULT 0,
  "secreto_2fa" varchar(255) DEFAULT NULL,
  "notificacion_correo" varchar(255) NOT NULL DEFAULT 'all',
  "notificacion_sistema" varchar(255) NOT NULL DEFAULT 'all',
  "perfil_publico" smallint NOT NULL DEFAULT 1,
  "ultimo_acceso" datetime DEFAULT NULL,
  "ultimo_acceso_ip" varchar(255) DEFAULT NULL,
  "token_recordar" varchar(100) DEFAULT NULL,
  "created_at" timestamp(0) without time zone,
  "updated_at" timestamp(0) without time zone,
  UNIQUE ("correo")
) 